### ISSUE TITLE
Add peer dependencies to play nice with webpack

### ISSUE THREAD

**Issue by arimus** [rajan-g/angular2-google-place-autocomplete#12]
I found an issue with the module not declaring peer dependencies for @angular core modules, which causes serious issues with Webpack. Webpack traverses the dep trees and ends up with 2 copies of angular core libs in the tree, which is an issue itself, but particularly an issue if they are different versions.

Something like the following. You'll notice most angular2 modules don't end up fetching @angular core libs into their node_modules section, because they use peer deps.

```
  "peerDependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0"
  },
```

And for reference: https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by rajan-g** [comment]
Hi arimus ,
       Thank you for your feedback, I will move angular dependency in dev dependency on future releade
