### ISSUE TITLE
Facing an issue when using AOT Compilation to make bundle file

### ISSUE THREAD

**Issue by gaganmurghai** [rajan-g/angular2-google-place-autocomplete#14]
I have setup a new angular2 app and place this repo directives folder and app.component.ts and app.module.ts . This way Google place autocomplete is working fine in my application . But when making Bundle file usig AOT process as mentioned in Angular documentation , i m getting following error:

> aot/app/company/add-staff.component.ngfactory.js (506:48) 'Wrapper_GoogleplaceDirective' is not exported by 'aot/app/directives/googleplace.directive.ngfactory.js'

Can Anyone help me in solving this issue

**Comment by rajan-g** [comment]
Hi gaganmurghai ,
I have released as module please try now
