### ISSUE TITLE
http://localhost:3000/traceur

### ISSUE THREAD

**Issue by theromie** [rajan-g/angular2-google-place-autocomplete#19]
systemjs.config.js
map: `'angular2-google-map-auto-complete': 'npm:angular2-google-map-auto-complete'`
package: `'angular2-google-map-auto-complete': {
                main: 'directives/index.js',
                defaultExtension: 'js'
            }`

module.ts
`import {GoogleplaceDirective} from 'angular2-google-map-auto-complete/directives/googleplace.directive';`
in decalrations:[GoogleplaceDirective]

giving http://localhost:3000/traceur any idea?

**Comment by rajan-g** [comment]
You are not loading resource properly. Check network tab in browser console
Check with demo code from http://www.angular2modules.com/
