### ISSUE TITLE
Limit results to specific place types

### ISSUE THREAD

**Issue by escarabin** [rajan-g/angular2-google-place-autocomplete#2]
Hi!

First, thank you for sharing your code. I am using it for a quite big project and I have to filter the places results to a specific type (like regions, geocode, establishements...) see : https://developers.google.com/places/supported_types

I don't see any way to do it actually. It looks like I have to pass a parameter 'types' in the URL but I do not find the URL inside your code.

May someone give me a little help on that?

Best

**Comment by Muthu2020** [comment]
Actually, we didn't limit the results from google places. It will retrieve the places from google map based on user input. If you want to filter according to types, you have to take the place object. 
May be you have an idea to filter the places by types.

Inside of place object you have 3 properties. They are geocode, address, regions.

**Comment by escarabin** [comment]
Ok, thanks for your quick reply. Indeed, I didn't realise you were using Google Maps API instead of Places's.
