### ISSUE TITLE
How to change input text to textarea input field?

### ISSUE THREAD

**Issue by 02harleen** [rajan-g/angular2-google-place-autocomplete#25]
Hi, I am using this plugin by this work file with input field text. But I am trying to use in textarea, this is showing error:- 
error :- `InvalidValueError: not an instance of HTMLInputElement`
Please help me to use in text area like this:- `<textarea placeholder=" text " googleplace></textarea>`

**Comment by rajan-g** [comment]
js?libraries=places&sensor=false:40 InvalidValueError: not an instance of HTMLInputElement
error generated by google. but it is working o)
 <textarea type="text" [(ngModel)] = "address"  (setAddress) = "getAddress($event)" googleplace></textarea>
