### ISSUE TITLE
I have import this module file my CommonModule but this package does not import?  

### ISSUE THREAD

**Issue by 02harleen** [rajan-g/angular2-google-place-autocomplete#31]
Error:- 
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at new BrowserModule (platform-browser.es5.js:4161)

How to solve this error. Because I have used this place in this module component.

**Comment by rajan-g** [comment]
I have upgraded. please try now if you have same issue give me some more details

**Comment by 02harleen** [comment]
The Same issue occurs. I have import this file my customer module but show same issue. 
Angular version:- 4.3.6
typescript:2.4.2

Please tell us?

**Comment by rajan-g** [comment]
2.0.8 version  released with this issue fix please check now
