### ISSUE TITLE
How to get address, pin_code, city, state etc using this package? 

### ISSUE THREAD

**Issue by 02harleen** [rajan-g/angular2-google-place-autocomplete#32]
Hi, In this package only One function this function get the address but does not get the complete address details. Please tell us how it is possible?

**Comment by rajan-g** [comment]
callback return complete google place object you can get all details from there. kindly debug and get it.
below structure is a sample object of place 
{
    "address_components": [
        {
            "long_name": "Chennai",
            "short_name": "Chennai",
            "types": [
                "locality",
                "political"
            ]
        },
        {
            "long_name": "Chennai",
            "short_name": "Chennai",
            "types": [
                "administrative_area_level_2",
                "political"
            ]
        },
        {
            "long_name": "Tamil Nadu",
            "short_name": "TN",
            "types": [
                "administrative_area_level_1",
                "political"
            ]
        },
        {
            "long_name": "India",
            "short_name": "IN",
            "types": [
                "country",
                "political"
            ]
        }
    ],
    "adr_address": "<span class=\"locality\">Chennai</span>, <span class=\"region\">Tamil Nadu</span>, <span class=\"country-name\">India</span>",
    "formatted_address": "Chennai, Tamil Nadu, India",
    "geometry": {
        "location": {
            "lat": 13.0826802,
            "lng": 80.27071840000008
        },
        "viewport": {
            "south": 12.8338848,
            "west": 80.08170070000006,
            "north": 13.2611661,
            "east": 80.33632280000006
        }
    },
    "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
    "id": "1fcd7bfd9f29e59c4de19320b184468f69e301da",
    "name": "Chennai",
    "photos": [
        {
            "height": 1080,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/115306491091237167643/photos\">Sethunath V</a>"
            ],
            "width": 1920
        },
        {
            "height": 2304,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/105360148693365396981/photos\">Ajay Simha</a>"
            ],
            "width": 4096
        },
        {
            "height": 2368,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/101077238330867256129/photos\">naresh.garikapati 9640156933</a>"
            ],
            "width": 4208
        },
        {
            "height": 1080,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/110880131174848884758/photos\">rajkumar kannuru</a>"
            ],
            "width": 1920
        },
        {
            "height": 3120,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/112182206465185784122/photos\">Saravanan Jagadeesan</a>"
            ],
            "width": 4160
        },
        {
            "height": 1200,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/112385574098053163347/photos\">Nurul Islam</a>"
            ],
            "width": 1920
        },
        {
            "height": 1836,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/107586840618653530728/photos\">sanjay hakkim</a>"
            ],
            "width": 3264
        },
        {
            "height": 2322,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/112909918578472410074/photos\">Vikas Darekar</a>"
            ],
            "width": 4128
        },
        {
            "height": 1080,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/115306491091237167643/photos\">Sethunath V</a>"
            ],
            "width": 1920
        },
        {
            "height": 1440,
            "html_attributions": [
                "<a href=\"https://maps.google.com/maps/contrib/104331203838320895342/photos\">Survivor ISS</a>"
            ],
            "width": 2560
        }
    ],
    "place_id": "ChIJYTN9T-plUjoRM9RjaAunYW4",
    "reference": "CmRbAAAAz8Y5QeWlsGDccbZT9eFHZxD2pBKr1Qd4Pquu_VM-6gIcRidzL82_dQi9ij2G1UtmtUXZGYAiduR3Z9z8JqPl6UKhe6nfEa-GC2NR9L4ShjNkGtufpIBerQ_GeO-UrryNEhBrWi0rzn4CFHMxZm5fmDpYGhTQHVj2TdmMoKLNiAt6_lZ-NvyWqQ",
    "scope": "GOOGLE",
    "types": [
        "locality",
        "political"
    ],
    "url": "https://maps.google.com/?q=Chennai,+Tamil+Nadu,+India&ftid=0x3a5265ea4f7d3361:0x6e61a70b6863d433",
    "utc_offset": 330,
    "vicinity": "Chennai",
    "html_attributions": []
}
