### ISSUE TITLE
'$' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by bencameron00** [rajan-g/angular2-google-place-autocomplete#33]
When I am running 'npm install' I am getting the below console error...

> angular2-google-map-auto-complete@2.0.7 postinstall C...\node_modules\angular2-google-map-a
uto-complete
> $(npm bin)/typings install
'$' is not recognized as an internal or external command,
operable program or batch file.

My packages file looks like this...

{
  "name": "tilecase",
  "version": "1.0.0",
  "description": "TileCase",
  "scripts": {
    "start": "webpack-dev-server --config config/webpack.dev.js --inline --progress --content-base src/",
    "test": "karma start",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/bencameron00/TileCase.V2.UI.git"
  },
  "license": "UNLICENSED",
  "dependencies": {
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6",
    "@types/googlemaps": "^3.26.1",
    "@types/jquery": "^3.2.12",
    "angular2-google-map-auto-complete": "^2.0.7",
    "angular2-google-maps": "^0.15.0",
    "angular2-infinite-scroll": "^0.2.9",
    "angular2-jwt": "^0.1.28",
    "angular2-moment": "^0.8.2",
    "angulartics2": "^1.6.3",
    "core-js": "^2.4.1",
    "googlemaps": "^1.12.0",
    "html-webpack-plugin": "^2.26.0",
    "jquery": "^3.1.1",
    "karma-webpack": "^1.8.1",
    "ng2-bootstrap": "^1.2.6",
    "ng2-facebook-sdk": "^1.2.0",
    "ng2-file-upload": "^1.2.0",
    "ng2-img-cropper": "^0.7.7",
    "ng2-page-scroll": "^3.2.3",
    "ng2-social-share": "^0.0.10",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.0.3",
    "signalr": "^2.2.1",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@types/googlemaps": "^3.25.37",
    "@types/jquery": "^3.2.12",
    "angular2-jwt": "^0.1.24",
    "css-loader": "^0.23.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.8",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "ng2-facebook-sdk": "^1.1.0",
    "node-sass": "^3.8.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "sass-loader": "^3.2.1",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.2",
    "typescript": "^2.2 ",
    "typings": "^2.1.1",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0",
    "webpack-svgstore-plugin": "^3.0.0"
  }
}

**Comment by developersenthil** [comment]
Hey, am also getting this same error. Have you find any solution?

**Comment by Hulker** [comment]
Hey, am also getting this same error. Have you find any solution?

**Comment by tobieeniafe** [comment]
So I was able to solve it [here](https://github.com/tobieeniafe/angular2-googlemap-autocomplete) hope it helps
