### ISSUE TITLE
typings error when installing via npm and yarn

### ISSUE THREAD

**Issue by tobieeniafe** [rajan-g/angular2-google-place-autocomplete#34]
typings error when installing via npm and yarn. fails to install

**Comment by yosephcsantos** [comment]
when installing via npm
![image](https://user-images.githubusercontent.com/1666089/31121408-778ea924-a80e-11e7-8d53-2d2d820f012a.png)

**Comment by rajan-g** [comment]
latest version released with fix upgrade and check

**Comment by d89** [comment]
Still happens in version 2.0.8:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-google-map-auto-complete@2.0.8 postinstall: `$(npm bin)/typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-google-map-auto-complete@2.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-11-19T21_20_46_674Z-debug.log
```

My environment:
```
User@WINDOWS ~
$ node -v
v8.8.1

User@WINDOWS ~
$ npm -v
5.0.3
```

**Comment by d89** [comment]
Can you take a look, please @rajan-g ? This is the only node package in my project, that is executing `$(npm bin)/typings install` which is causing my `npm install` to fail.

**Comment by tobieeniafe** [comment]
@d89 I solved it here https://github.com/tobieeniafe/angular2-googlemap-autocomplete

**Comment by d89** [comment]
Is it a 1:1 fork with just the `$(npm bin)/typings install` removed?

**Comment by tobieeniafe** [comment]
No. I was able to find a way around it with the angular 2 Google map module. You can check it out

**Comment by rajan-g** [comment]
So sorry for too delay response. We have to re-move  "postinstall": "$(npm bin)/typings install". I will do and commit soon

**Comment by rajan-g** [comment]
Easy way you can use https://github.com/rajan-g/angular2-google-place-autocomplete/blob/master/directives/googleplace.directive.ts

**Comment by Segfaultd** [comment]
@rajan-g Hey, have u been able to implement?

**Comment by rajan-g** [comment]
I am so sorry for this much delay, I have fixed that typing issue. Enjoy
