### ISSUE TITLE
npm install not working.

### ISSUE THREAD

**Issue by nashmaniac** [rajan-g/angular2-google-place-autocomplete#36]
`angular2-google-map-auto-complete@2.0.8 postinstall /path_to_directory/node_modules/angular2-google-map-auto-complete
> $(npm bin)/typings install

>sh: /path_to_directory/node_modules/angular2-google-map-auto-complete/node_modules/.bin/typings: No such file or directory`

npm install is not working.
angular-cli: 1.5.0
angular version: 5.0

can you help  ?

**Comment by rajan-g** [comment]
do npm typings install -g
