### ISSUE TITLE
How to use this libary with model driven tamplate?

### ISSUE THREAD

**Issue by efstathiosntonas** [rajan-g/angular2-google-place-autocomplete#4]
Can you please give me an example on how to use this library with model driven forms in RC.6?

Thanks

**Comment by Muthu2020** [comment]
still not yet upgraded into RC.6.

**Comment by efstathiosntonas** [comment]
the code works on RC.6 with no issues, the input box is showing results and console log them fine!

the real issue is not RC.6 but how to grab the values from the input box when using model driven forms. I m new to ng2 and i m kinda lost.

**Comment by Muthu2020** [comment]
Can you send me the input tag?

**Comment by efstathiosntonas** [comment]
`<input type="text" class="form-control" [(ngModel)]="address" placeholder="" ngControl="address" (setAddress)="getAddress($event)" required id="lostArea" googleplace [ngModelOptions]="{standalone: true}"/>`

and this is the getAddress function:
` public address: Object;

  getAddress(place: Object) {
    this.address = place['formatted_address'];
    var location = place['geometry']['location'];
    var lat = location.lat();
    var lng = location.lng();
  }`

**Comment by Muthu2020** [comment]
Thanks for sending me for better understanding to resolve your issue.
I think you would probably use the address as a global object in component.Once you could submit your form,you can able to see the binded object in address variable while you have to print it in console.log('address',this.address).
It will show you an entire value.
