### ISSUE TITLE
How to put in my Google Place API key?

### ISSUE THREAD

**Issue by Solan85** [rajan-g/angular2-google-place-autocomplete#6]
I do not see any place where I can put in my API key. Though this module is running successfully on my machine with angular2 app. I see calls being made to google api and getting results properly. But I am not sure which API key its using.

Please help. Our app is going to production in few hours.

**Comment by rajan-g** [comment]
It is easy. just want to add api key in your lib param like below:
http://maps.googleapis.com/maps/api/js?libraries=places&key=AIza*******************
You can get this key from google console

**Comment by stepanzarubin** [comment]
Any suggestions of how to save dev/prod keys as params and then use at script tag?

**Comment by rajan-g** [comment]
use template builder for adding js libs, example jade. this will support environment variable binding support dynamically
